version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  is-green:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # fallback to using the latest cache if no exact match is found

      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh
      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Type check
          command: yarn type-check

      - run:
          name: Test
          command: yarn test

      - run:
          name: Build rollup
          command: yarn build:rollup

      - persist_to_workspace:
          root: ~/repo
          paths: .
  prerelease:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build package
          command: yarn build:rollup
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Release "next" version
          command: npm run release -- --dry-run --no-verify --prerelease next

workflows:
  version: 2
  test:
    jobs:
      - is-green
  run-prerelease:
    jobs:
      - is_green
      - prerelease:
          requires:
            - is_green
          filters:
            branches:
              only: chore/automate-prerelease # TODO this should be "dev"
