export const fontFamilies = {
  headerFontFamily: [
    `Futura PT`,
    `-apple-system`,
    `BlinkMacSystemFont`,
    `Segoe UI`,
    `Roboto`,
    `Oxygen`,
    `Ubuntu`,
    `Cantarell`,
    `Fira Sans`,
    `Droid Sans`,
    `Helvetica Neue`,
    `Arial`,
    `sans-serif`,
  ].join(),
  bodyFontFamily: [
    `-apple-system`,
    `BlinkMacSystemFont`,
    `Segoe UI`,
    `Roboto`,
    `Helvetica Neue`,
    `Arial`,
    `Noto Sans`,
    `sans-serif`,
    `Apple Color Emoji`,
    `Segoe UI Emoji`,
    `Segoe UI Symbol`,
    `Noto Color Emoji !important`,
  ].join(),
  monospaceFontFamily: [
    `SFMono-Regular`,
    `Menlo`,
    `Monaco`,
    `Consolas`,
    `Liberation Mono`,
    `Courier New`,
    `monospace`,
  ].join(),
}
